import AppKit

/// Detects pasteboard entries that third-party apps explicitly marked as
/// concealed/transient (the nspasteboard.org convention) as well as a few well-known
/// password-manager markers. We skip these entirely — they never enter the history.
enum SensitiveContentFilter {
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("com.googlecode.iterm2.SecureInput"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
    ]

    static func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        let types = Set(pasteboard.types ?? [])
        for t in concealedTypes where types.contains(t) {
            return true
        }
        return false
    }
}
